<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <DevelopmentDependency>true</DevelopmentDependency>
    <Deterministic>true</Deterministic>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_AddAnalyzersToOutput</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)../../Version.props" />

  <PropertyGroup>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>FlashOWare.Analyzers</PackageId>
    <Title>FlashOWare.Analyzers</Title>
    <Authors>FlashOWare;Flash0ver</Authors>
    <Company>FlashOWare</Company>
    <Product>FlashOWare.CodeAnalysis</Product>
    <Description>Common compiler extensions for C# and Visual Basic projects, including Diagnostic-Analyzers &amp; Diagnostic-Suppressors, also Providers for Code-Refactorings, Code-Fixes, and Completions.</Description>
    <Copyright>© FlashOWare and Contributors.</Copyright>
    <PackageProjectUrl>https://github.com/FlashOWare/roslyn-components-compiler-extensions-documentation</PackageProjectUrl>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/FlashOWare/roslyn-components-compiler-extensions.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>f[0];F0;FlashOWare;CodeAnalysis;Roslyn;Analyzers;CSharp;C#;</PackageTags>
    <PackageReleaseNotes>https://github.com/FlashOWare/roslyn-components-compiler-extensions/blob/main/source/FlashOWare.Analyzers/CHANGELOG.md</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/README.md" Visible="true" />
    <None Condition=" '$(VersionSuffix)' == '' " Include="../../../../resources/FlashOWare.png" Pack="true" PackagePath="/Icon.png" Visible="true" />
    <None Condition=" '$(VersionSuffix)' != '' " Include="../../../../resources/FlashOWare-Preview.png" Pack="true" PackagePath="/Icon.png" Visible="true" />
  </ItemGroup>

  <ItemGroup>
    <None Include="build/*.props" Pack="true" PackagePath="/build" Visible="true" />
    <None Include="build/*.targets" Pack="true" PackagePath="/build" Visible="true" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../roslyn/FlashOWare.Analyzers.CSharp.Roslyn/FlashOWare.Analyzers.CSharp.Roslyn4_13.csproj" SetTargetFramework="TargetFramework=netstandard2.0" DestinationSubDirectory="roslyn4.13/" />
  </ItemGroup>

  <Target Name="_AddAnalyzersToOutput">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)/roslyn4.13/FlashOWare.Analyzers.CSharp.Roslyn4_13.dll" PackagePath="analyzers/dotnet/roslyn4.13/cs/" />
    </ItemGroup>
  </Target>

</Project>
