<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);ROSLYN4_13_OR_GREATER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" VersionOverride="4.13.0" />
  </ItemGroup>

</Project>
