@FlashOWare.Analyzers.CSharp.Demo.WebApiApp_HostAddress = http://localhost:5116

GET {{FlashOWare.Analyzers.CSharp.Demo.WebApiApp_HostAddress}}/
Accept: application/json

###

GET {{FlashOWare.Analyzers.CSharp.Demo.WebApiApp_HostAddress}}/assembly
Accept: application/json

###
